- name: configure docker-ce and setting up httpd on container
  hosts: httpd_container
  tasks:
          - name: Configure yum for docker
            yum_repository:
                    name: dockerepo
                    description: dockerrepo
                    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                    gpgcheck: no
                    enabled: yes
          - name: Installing Docker package
            package:
                    name:
                            - "docker-ce-18.09.1-3.el7.x86_64"
                    state: present  
          - name: Start Docker service
            service:
                    name: "docker"
                    state: started
                    enabled: yes
          - name: Installing docker sdk 
            command: pip3 install docker
          - name: Create folder with webpages
            file:
                    path: /ansible_code/website
                    state: directory
          - name: Copy webpages
            copy:
                    src: "/ansible_code/index.html"
                    dest: "/ansible_code/website"

          - name: Launch container          
            docker_container:
                    name: ansiblewebsite
                    image: httpd:latest
                    state: started
                    exposed_ports:
                            - "80"
                    ports:
                            - "3333:80"
                    volumes:
                            - /ansible_code/website:/usr/local/apache2/htdocs/
         
